### ISSUE TITLE
Problem with slider in Chrome

### ISSUE THREAD

**Issue by ninfaj** [4teamwork/ftw.slider#8]
You have to set something like:

``` CSS
.sliderPane { height: 500px; }
```

Otherwise Google Chrome starts with the last pane and continues with the second...
Maybe we should define a size for the slider images.
